services: # this defines all container (microservices and dbs)
  # ====================
  # Auth Service + DB
  # ====================

  auth-service:
    build:
      context: ./services/auth_service # build the image from "./services/auth_service/Dockerfile"
      target: dev
    ports:
      - "3001:3000" # exposed in 3001 outside of the Docker and run on 3000 within the Docker
    env_file:
      - ./services/auth_service/.env
    depends_on:
      - auth-db
      - redis
      - rabbitmq
    volumes:
      - ./services/auth_service:/app

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # ====================
  # Booking Service + DB
  # ====================

  booking-service:
    build:
      context: ./services/booking_service
      target: dev
    ports:
      - "3002:3000" # exposed in 3001 outside of the Docker and run on 3000 within the Docker
    env_file:
      - ./services/booking_service/.env
    depends_on:
      - booking-db
      - redis
      - rabbitmq
    volumes:
      - ./services/booking_service:/app

  booking-db:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - booking_db_data:/var/lib/postgresql/data

  # ====================
  # Flight Service + DB
  # ====================

  flight-service:
    build:
      context: ./services/flight_service
      target: dev
    ports:
      - "3003:3000" # exposed in 3001 outside of the Docker and run on 3000 within the Docker
    env_file:
      - ./services/flight_service/.env
    depends_on:
      - flight-db
      - redis
      - rabbitmq
    volumes:
      - ./services/flight_service:/app

  flight-db:
    image: postgres:15
    environment:
      POSTGRES_DB: flight_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - flight_db_data:/var/lib/postgresql/data

  # ====================
  # Payment Service + DB
  # ====================

  payment-service:
    build:
      context: ./services/payment_service
      target: dev
    ports:
      - "3004:3000" # exposed in 3001 outside of the Docker and run on 3000 within the Docker
    env_file:
      - ./services/payment_service/.env
    depends_on:
      - payment-db
      - redis
      - rabbitmq
    volumes:
      - ./services/payment_service:/app

  payment-db:
    image: postgres:15
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - payment_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass arecoreredis@321
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password@321
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

volumes:
  auth_db_data:
  booking_db_data:
  flight_db_data:
  payment_db_data:
  redis_data:
  rabbitmq_data:
  rabbitmq_log:
